# Generated by Django 3.2.4 on 2021-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField(max_length=100)),
                ('principal', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Collegelist',
        ),
    ]
